---
# ------------------------------------------------------------------------
# Telekom Security - Compliance Automation
# SSH (3.04)
# Handlers
# ------------------------------------------------------------------------

- name: restart sshd
  service:
    name: '{{ sshd_service_name }}'
    state: restarted
  when: config_restart_handlers|bool
