---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: "Install required packages for testing"
      apt:
        name:
          - openssh-server
        state: present